[book]
authors = ["Yuxuan Shui"]
language = "en"
multilingual = false
src = "src"
title = "yshui --log-level=trace"

[output.html]
default-theme = "coal"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
