name: GitHub Pages

on:
  push:
    branches:
      - doc
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Read .env
        id: mdbook-version
        run: |
          . ./.env
          echo "MDBOOK_VERSION=${MDBOOK_VERSION}" >> $GITHUB_OUTPUT

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '${{ steps.mdbook-version.outputs.MDBOOK_VERSION }}'

      - name: Build
        run: mdbook build -d _site

      - name: Copy assets
        continue-on-error: true
        run: cp -rv assets _site/

      - name: Upload
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

